spring.datasource.url=jdbc:mysql://localhost:3306/workstudy
spring.datasource.username=root
spring.datasource.password=Hasini@1623

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8080